name: Test package
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '18'

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: npm install

      # Tests
      - name: Run tests
        run: npm test

      - name: Coveralls
        uses: coverallsapp/github-action@v2

      # Build
      - name: Run build
        run: npm run build